language: node_js
node_js: '8'

cache:
  yarn: true
  directories:
    - node_modules

before_install:


install:
  - yarn --frozen-lockfile --non-interactive
  - yarn global add @vue/cli
  - yarn run 'test:unit'
